USE dbTeste
GO

CREATE TABLE dbo.tbcliente(
	[CLIENTE_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](60) NOT NULL,
	[TIPO_PESSOA] [char](1) NOT NULL,
	[CPF_CNPJ] [varchar](14) NOT NULL,
	[RG_IE] [varchar](15) NULL,
	[LAGRADOURO] [varchar](55) NULL,
	[BAIRRO] [varchar](30) NULL,
	[NUMERO] [varchar](15) NULL,
	[COMPLEMENTO] [varchar](50) NULL,
	[CIDADE] [varchar](30) NULL,
	[CEP] [varchar](8) NULL,
	[UF] [varchar](2) NULL,
	[PAIS] [varchar](30) NULL,
	[DATA_INCLUSAO] [smalldatetime] NULL,
	[ATIVO] [BIT] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CLIENTE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE dbo.tbcliente ADD  DEFAULT (1) FOR [ATIVO]
GO

CREATE TRIGGER tgAfterInsert_tbCliente ON tbCliente
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;
    
    UPDATE TBCLIENTE SET DATA_INCLUSAO = GETDATE(), ATIVO = 1
     WHERE CLIENTE_ID IN (SELECT CLIENTE_ID FROM INSERTED)
END;
GO

ALTER TABLE [dbo].[tbCliente] ENABLE TRIGGER [tgAfterInsert_tbCliente];
